const events_data = [
  { id: 0, name: 'Slime Mould', cat: 'tech' },
  { id: 1, name: 'Eschewal', cat: 'cult' },
  { id: 2, name: 'CANTILEVER TOWER', cat: 'tech' },
  { id: 3, name: 'SoLiquid', cat: 'cult' },
  { id: 4, name: 'Alignment', cat: 'tech' },
  { id: 5, name: 'CSS Battle ', cat: 'tech' },
  { id: 6, name: 'Expo', cat: 'cult' },
  { id: 7, name: 'Innovator', cat: 'tech' },
  { id: 8, name: 'The Maze Runner', cat: 'cult' },
  { id: 9, name: 'Spooky House', cat: 'cult' },
  { id: 10, name: 'Circuit saga', cat: 'tech' },
  { id: 11, name: 'Laser Tag', cat: 'cult' },
  { id: 12, name: 'Project Presentation', cat: 'tech' },
  { id: 13, name: 'Paper Presentation', cat: 'odd' },
  { id: 14, name: 'Prison Breakout', cat: 'odd' },
  { id: 15, name: 'Kaboom', cat: 'odd' },
  { id: 16, name: 'Robot controlled vehicle race', cat: 'tech' },
  { id: 17, name: 'Mechanical Gala', cat: 'odd' },
  { id: 18, name: 'Scary House', cat: 'cult' },
  { id: 19, name: 'Epic materials', cat: 'tech' },
  { id: 20, name: 'Dirt Car Race', cat: 'odd' },
  { id: 21, name: 'Project Expo', cat: 'cult' },
  { id: 22, name: 'Hydroponic System', cat: 'odd' },
  { id: 23, name: 'Vertical Farming', cat: 'odd' },
  { id: 24, name: 'Talent Hunt ', cat: 'cult' },
  { id: 25, name: 'Movie screening', cat: 'cult' },
  { id: 27, name: 'Classdo', cat: 'odd' },
  { id: 28, name: 'Nacho Nacho', cat: 'cult' },
  { id: 29, name: 'Music Mania 2023', cat: 'cult' },
  { id: 30, name: 'Noraebang 2023', cat: 'cult' },
  { id: 31, name: 'Anthashkari Blitz', cat: 'odd' },
  { id: 32, name: 'Robo War', cat: 'odd' },
  { id: 33, name: 'Solution Challenge', cat: 'odd' },
  { id: 34, name: 'Startup Expo', cat: 'odd' },
  { id: 35, name: 'Arz Kiya Hai', cat: 'odd' },
  { id: 36, name: 'Ludo-ver and Over Again', cat: 'odd' },
  { id: 37, name: 'Baby Shark Tank', cat: 'cult' },
  { id: 38, name: 'Lock And Key', cat: 'cult' },
  { id: 39, name: 'Capture to correct', cat: 'cult' },
  { id: 40, name: 'Phrases to make over', cat: 'cult' },
  { id: 41, name: 'Solve Me', cat: 'cult' },
  { id: 42, name: 'Drama', cat: 'cult' },
  { id: 43, name: 'Pot painting', cat: 'cult' },
  { id: 44, name: 'Graffiti wall painting', cat: 'cult' },
  { id: 45, name: 'Balancing the Four Quadrants of Life', cat: 'cult' },
];
export default events_data;
