const events_data = [
  {
    id: 0,
    name: 'Slime Mould',
    cat: 'tech',
    link: 'https://i.ibb.co/5rYkHr3/BEA.jpg',
  },
  {
    id: 1,
    name: 'Eschewal',
    cat: 'cult',
    link: 'https://i.ibb.co/5rYkHr3/BEA.jpg',
  },
  {
    id: 2,
    name: 'CANTILEVER TOWER',
    cat: 'tech',
    link: 'https://i.ibb.co/tPfnVhj/CEA-logo.png',
  },
  {
    id: 3,
    name: 'SoLiquid',
    cat: 'cult',
    link: 'https://i.ibb.co/QX3ryxw/Ch-EA-New-Logo.png',
  },
  {
    id: 4,
    name: 'Alignment',
    cat: 'tech',
    link: 'https://i.ibb.co/QX3ryxw/Ch-EA-New-Logo.png',
  },
  {
    id: 5,
    name: 'CSS Battle ',
    cat: 'tech',
    link: 'https://i.ibb.co/rG8hpKL/CSEA.jpg',
  },
  {
    id: 6,
    name: 'Expo',
    cat: 'cult',
    link: 'https://i.ibb.co/rG8hpKL/CSEA.jpg',
  },
  {
    id: 7,
    name: 'Innovator',
    cat: 'tech',
    link: 'https://i.ibb.co/rG8hpKL/CSEA.jpg',
  },
  {
    id: 8,
    name: 'The Maze Runner',
    cat: 'cult',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 9,
    name: 'Spooky House',
    cat: 'cult',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 10,
    name: 'Circuit saga',
    cat: 'tech',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 11,
    name: 'Laser Tag',
    cat: 'cult',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 12,
    name: 'Project Presentation',
    cat: 'tech',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 13,
    name: 'Paper Presentation',
    cat: 'odd',
    link: 'https://i.ibb.co/L6t0Drn/ECEA.jpg',
  },
  {
    id: 14,
    name: 'Prison Breakout',
    cat: 'odd',
    link: 'https://i.ibb.co/hWLZJBd/EEA.jpg',
  },
  {
    id: 15,
    name: 'Kaboom',
    cat: 'odd',
    link: 'https://i.ibb.co/hWLZJBd/EEA.jpg',
  },
  {
    id: 16,
    name: 'Robot controlled vehicle race',
    cat: 'tech',
    link: 'https://i.ibb.co/Fsj6HCL/MEA-logo.jpg',
  },
  {
    id: 17,
    name: 'Mechanical Gala',
    cat: 'odd',
    link: 'https://i.ibb.co/Fsj6HCL/MEA-logo.jpg',
  },
  {
    id: 18,
    name: 'Scary House',
    cat: 'cult',
    link: 'https://i.ibb.co/0n1JCrW/MMEA-LOGO-B-BG.png',
  },
  {
    id: 19,
    name: 'Epic materials',
    cat: 'tech',
    link: 'https://i.ibb.co/0n1JCrW/MMEA-LOGO-B-BG.png',
  },
  {
    id: 20,
    name: 'Dirt Car Race',
    cat: 'tech',
    link: 'https://i.ibb.co/z6mMmdd/AIR.jpg',
  },
  {
    id: 21,
    name: 'Project Expo',
    cat: 'cult',
    link: 'https://i.ibb.co/z6mMmdd/AIR.jpg',
  },
  {
    id: 22,
    name: 'Hydroponic System',
    cat: 'tech',
    link: 'https://i.ibb.co/c3Tf8KT/Screenshot-20221227-141939-Instagram.jpg',
  },
  {
    id: 23,
    name: 'Vertical Farming',
    cat: 'tech',
    link: 'https://i.ibb.co/c3Tf8KT/Screenshot-20221227-141939-Instagram.jpg',
  },
  {
    id: 24,
    name: 'Talent Hunt ',
    cat: 'cult',
    link: 'https://i.ibb.co/DpTGtkp/CHITRAM-Logo.png',
  },
  {
    id: 25,
    name: 'Movie screening',
    cat: 'cult',
    link: 'https://i.ibb.co/DpTGtkp/CHITRAM-Logo.png',
  },
  {
    id: 27,
    name: 'Classdo',
    cat: 'cult',
    link: 'https://i.ibb.co/Z6CPd8c/DND.jpg',
  },
  {
    id: 28,
    name: 'Nacho Nacho',
    cat: 'cult',
    link: 'https://i.ibb.co/Z6CPd8c/DND.jpg',
  },
  {
    id: 29,
    name: 'Music Mania 2023',
    cat: 'cult',
    link: 'https://i.ibb.co/bBptSTh/Dhwani-Music-Club.png',
  },
  {
    id: 30,
    name: 'Noraebang 2023',
    cat: 'cult',
    link: 'https://i.ibb.co/bBptSTh/Dhwani-Music-Club.png',
  },
  {
    id: 31,
    name: 'Anthashkari Blitz',
    cat: 'cult',
    link: 'https://i.ibb.co/bBptSTh/Dhwani-Music-Club.png',
  },
  {
    id: 32,
    name: 'Robo War',
    cat: 'tech',
    link: 'https://i.ibb.co/GRtWMg0/Eyantra-club.jpg',
  },
  {
    id: 33,
    name: 'Solution Challenge',
    cat: 'tech',
    link: 'https://i.ibb.co/bBptSTh/Dhwani-Music-Club.png',
  },
  {
    id: 34,
    name: 'Startup Expo',
    cat: 'tech',
    link: 'https://i.ibb.co/N3m6SRm/E-I-cell-dark-theme-logo.jpg',
  },
  {
    id: 35,
    name: 'Arz Kiya Hai',
    cat: 'cult',
    link: 'https://i.ibb.co/fpPccG3/lnd.jpg',
  },
  {
    id: 36,
    name: 'Ludo-ver and Over Again',
    cat: 'cult',
    link: 'https://i.ibb.co/fpPccG3/lnd.jpg',
  },
  {
    id: 37,
    name: 'Baby Shark Tank',
    cat: 'cult',
    link: 'https://i.ibb.co/fpPccG3/lnd.jpg',
  },
  {
    id: 38,
    name: 'Lock And Key',
    cat: 'cult',
    link: 'https://i.ibb.co/w40cg4N/nve.jpg',
  },
  {
    id: 39,
    name: 'Capture to correct',
    cat: 'cult',
    link: 'https://i.ibb.co/w40cg4N/nve.jpg',
  },
  {
    id: 40,
    name: 'Phrases to make over',
    cat: 'cult',
    link: 'https://i.ibb.co/w40cg4N/nve.jpg',
  },
  {
    id: 41,
    name: 'Solve Me',
    cat: 'cult',
    link: 'https://i.ibb.co/w40cg4N/nve.jpg',
  },
  {
    id: 42,
    name: 'Drama',
    cat: 'cult',
    link: 'https://i.ibb.co/w40cg4N/nve.jpg',
  },
  {
    id: 43,
    name: 'Pot painting',
    cat: 'cult',
    link: 'https://i.ibb.co/L6kyhWw/pnp-club-Logo.jpg',
  },
  {
    id: 44,
    name: 'Graffiti wall painting',
    cat: 'cult',
    link: 'https://i.ibb.co/L6kyhWw/pnp-club-Logo.jpg',
  },
  {
    id: 45,
    name: 'Balancing the Four Quadrants of Life',
    cat: 'cult',
    link: 'https://i.ibb.co/C5ck2n5/Shreshtha-club.jpg',
  },
];
export default events_data;
